### ISSUE TITLE
Consuming tesseract (API?) in Windows 10

### ISSUE THREAD

**Issue by ddugovic** [pjwerneck/cookbot#1]
I'm attempting to port this bot to Windows 10!  In `cookbot/ocr.py` I have changed:

```
#libname = '/usr/lib/libtesseract.so.3'
#TESSDATA_PREFIX = '/usr/share/tesseract-ocr'
libname = 'C:/Program Files (x86)/Tesseract-OCR/libtesseract-3.dll'
TESSDATA_PREFIX = 'C:/Program Files (x86)/Tesseract-OCR/tessdata'

print libname
libtesseract = ctypes.cdll.LoadLibrary(libname)
```

However, I observe a WindowsError (even running standalone) and can't seem to find a way to make `ocr.py` do whatever it's designed to do (were it running on Linux).  Do you have general advice about how to use tesseract (or why `cookbot` consumes its API instead of running its executable)?  Thanks in advance.

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> libname = 'C:/Program Files (x86)/Tesseract-OCR/libtesseract-3.dll'
>>> print libname
C:/Program Files (x86)/Tesseract-OCR/libtesseract-3.dll
>>> libtesseract = ctypes.cdll.LoadLibrary(libname)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by pjwerneck** [comment]
@ddugovic You can probably replace the whole ctypes+libtesseract dance with pytesseract. Have you tried that?

**Comment by ddugovic** [comment]
@pjwerneck Excellent suggestion!  After that & after aligning the screenshot boxes I am now having [some success](https://github.com/ddugovic/cookbot/commits/windows).  Perhaps I need to experiment with the spell-checker...

(I changed some `logging.debug` to `logging.info` as I don't see how to enable debug logging).

```
python app.py run
    INFO - Starting...
    INFO - {'dbfile': 'cookbot.db', 'key_delay': 0.1, 'auto_accept': True, 'canary': True, 'test_recipes': None, 'func': <function _run at 0x000000000B928B38>, 'auto_order': False, 'loop_delay': 0.1}
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
    INFO - Cache hit (7681.7854997091445): u'with yellow dog'
with yellow dog
SELECT food, title, recipe, finished_at FROM recipes WHERE title = with yellow dog
['C:/Program Files (x86)/Tesseract-OCR/tesseract.exe', 'c:\\users\\gaming\\appdata\\local\\temp\\tess_gojgg2.bmp', 'c:\\users\\gaming\\appdata\\local\\temp\\tess_rqssj9', '-l', 'eng', '--psm', '3', '-c', 'tessedit_char_whitelist=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789,./!?()']
    INFO - Raw text: u'Jusf Mustard, please'
Traceback (most recent call last):
  File "app.py", line 92, in <module>
    main()
  File "app.py", line 69, in main
    args.func(args)
  File "app.py", line 26, in _run
    game.run()
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\bot.py", line 58, in run
    self.prepare()
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\bot.py", line 190, in prepare
    food = self.get_food()
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\bot.py", line 105, in get_food
    logging.error("Couldn't identify task: %r, %r" % (self.window.title, self.window.text))
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\window.py", line 103, in __getattr__
    value = getattr(self, 'get_' + attr)()
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\window.py", line 127, in get_text
    whitelist=string.letters + string.digits + ',./!?()')
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\ocr.py", line 66, in __call__
    text = self.spellchecker(text)
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\spellcheck.py", line 101, in __call__
    words = [self.correct(w) for w in words]
  File "C:\Users\Gaming\Desktop\cookbot\cookbot\spellcheck.py", line 77, in correct
    raise RuntimeError("No candidates for: %r" % word)
RuntimeError: No candidates for: u'jusf'
```

**Comment by pjwerneck** [comment]
@ddugovic Try adding "just" to the /data/SC_WORDS.csv file.

**Comment by ddugovic** [comment]
@pjwerneck Thanks, that works great!

**Comment by pjwerneck** [comment]
@ddugovic Would you mind sending a PR? I'll check if it works on linux.

**Comment by ddugovic** [comment]
@pjwerneck Certainly, I'd be glad to https://github.com/pjwerneck/cookbot/pull/2
